package gui;

/**
 *
 * @author emifu
 */
public class A_MenuServidor extends javax.swing.JFrame {

    /**
     * Creates new form I_MenuInicio
     */
    public A_MenuServidor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        estadisticas = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        crearPartida = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        crearMapa = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        atras = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Comic Book", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Menu Servidor");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 290, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estadisticas.setBackground(new java.awt.Color(255, 255, 255));
        estadisticas.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        estadisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadisticas.setText("Estadisticas");
        estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estadisticasMouseClicked(evt);
            }
        });
        jPanel1.add(estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 290, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearPartida.setBackground(new java.awt.Color(255, 255, 255));
        crearPartida.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        crearPartida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearPartida.setText("Crear Partida");
        crearPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearPartidaMouseClicked(evt);
            }
        });
        jPanel2.add(crearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 290, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crearMapa.setBackground(new java.awt.Color(255, 255, 255));
        crearMapa.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        crearMapa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearMapa.setText("Gestionar Ciudad");
        crearMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearMapaMouseClicked(evt);
            }
        });
        jPanel3.add(crearMapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 290, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        atras.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atras.setText("Atrás");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        jPanel4.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 60, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("Salir");
        jPanel5.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 60, 20));

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/menuServidor.png"))); // NOI18N
        fondo.setText("jLabel1");
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void crearMapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMapaMouseClicked
        B_GestionCiudades nf = new B_GestionCiudades();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearMapaMouseClicked

    private void crearPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearPartidaMouseClicked
        B_CrearPartida nf = new B_CrearPartida();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crearPartidaMouseClicked

    private void estadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estadisticasMouseClicked
        B_Estadisticas nf = new B_Estadisticas();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_estadisticasMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        A_ControlAcceso nf = new A_ControlAcceso();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_MenuServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_MenuServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atras;
    private javax.swing.JLabel crearMapa;
    private javax.swing.JLabel crearPartida;
    private javax.swing.JLabel estadisticas;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
