package gui;

import aplicacion.ManejoJSON;
import static aplicacion.ManejoJSON.borrarTodoJSON;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import logicadenegocios.*;
/**
 *
 * @author emifu
 */
public class B_GestionCiudades extends javax.swing.JFrame {
    
    private javax.swing.JPanel slotSeleccionado = null;
    public static int slotSeleccionadoNum = -1;
    private ArrayList<Ciudad> ciudades;
    
    private ArrayList<javax.swing.JPanel> slotsOcupados;
    private ArrayList<javax.swing.JLabel> slotsVacios;
    private ArrayList<javax.swing.JLabel> nombres;
    private ArrayList<javax.swing.JLabel> stats;
    private ArrayList<javax.swing.JLabel> imagenes;
    
    /**
     * Creates new form I_MenuInicio
     */
    public B_GestionCiudades() {
        this.ciudades= new ArrayList<>();
        this.slotsOcupados = new ArrayList<>();
        this.slotsVacios = new ArrayList<>();
        this.nombres = new ArrayList<>();
        this.stats = new ArrayList<>();
        this.imagenes = new ArrayList<>();        
        
        initComponents();
        this.setLocationRelativeTo(null);
        llenarListaObjetos();
        vaciarSlots();
        actualizarSlots();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new java.awt.Panel();
        slotCiudad1 = new javax.swing.JPanel();
        slotVacio1 = new javax.swing.JLabel();
        slotOcupado1 = new javax.swing.JPanel();
        slotNombre1 = new javax.swing.JLabel();
        slotStats1 = new javax.swing.JLabel();
        slotImagen1 = new javax.swing.JLabel();
        slotCiudad2 = new javax.swing.JPanel();
        slotVacio2 = new javax.swing.JLabel();
        slotOcupado2 = new javax.swing.JPanel();
        slotNombre2 = new javax.swing.JLabel();
        slotStats2 = new javax.swing.JLabel();
        slotImagen2 = new javax.swing.JLabel();
        slotCiudad3 = new javax.swing.JPanel();
        slotVacio3 = new javax.swing.JLabel();
        slotOcupado3 = new javax.swing.JPanel();
        slotNombre3 = new javax.swing.JLabel();
        slotStats3 = new javax.swing.JLabel();
        slotImagen3 = new javax.swing.JLabel();
        slotCiudad4 = new javax.swing.JPanel();
        slotVacio4 = new javax.swing.JLabel();
        slotOcupado4 = new javax.swing.JPanel();
        slotNombre4 = new javax.swing.JLabel();
        slotStats4 = new javax.swing.JLabel();
        slotImagen4 = new javax.swing.JLabel();
        slotCiudad5 = new javax.swing.JPanel();
        slotVacio5 = new javax.swing.JLabel();
        slotOcupado5 = new javax.swing.JPanel();
        slotNombre5 = new javax.swing.JLabel();
        slotStats5 = new javax.swing.JLabel();
        slotImagen5 = new javax.swing.JLabel();
        slotCiudad6 = new javax.swing.JPanel();
        slotVacio6 = new javax.swing.JLabel();
        slotOcupado6 = new javax.swing.JPanel();
        slotNombre6 = new javax.swing.JLabel();
        slotStats6 = new javax.swing.JLabel();
        slotImagen6 = new javax.swing.JLabel();
        slotCiudad7 = new javax.swing.JPanel();
        slotVacio7 = new javax.swing.JLabel();
        slotOcupado7 = new javax.swing.JPanel();
        slotNombre7 = new javax.swing.JLabel();
        slotStats7 = new javax.swing.JLabel();
        slotImagen7 = new javax.swing.JLabel();
        slotCiudad8 = new javax.swing.JPanel();
        slotVacio8 = new javax.swing.JLabel();
        slotOcupado8 = new javax.swing.JPanel();
        slotNombre8 = new javax.swing.JLabel();
        slotStats8 = new javax.swing.JLabel();
        slotImagen8 = new javax.swing.JLabel();
        slotCiudad9 = new javax.swing.JPanel();
        slotVacio9 = new javax.swing.JLabel();
        slotOcupado9 = new javax.swing.JPanel();
        slotNombre9 = new javax.swing.JLabel();
        slotStats9 = new javax.swing.JLabel();
        slotImagen9 = new javax.swing.JLabel();
        slotCiudad10 = new javax.swing.JPanel();
        slotVacio10 = new javax.swing.JLabel();

        slotOcupado10 = new javax.swing.JPanel();
        slotNombre10 = new javax.swing.JLabel();
        slotStats10 = new javax.swing.JLabel();
        slotImagen10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        modificar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        agregar1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        eliminar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        eliminartodo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        personajes = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        regresar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        fondociudad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setUndecorated(true);
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(900, 500));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotCiudad1.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad1.setOpaque(false);
        slotCiudad1.setPreferredSize(new java.awt.Dimension(440, 90));
        slotCiudad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot1(evt);
            }
        });
        slotCiudad1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio1.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio1.setText("<Vacio>");
        slotCiudad1.add(slotVacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado1.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre1.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre1.setText("Nombre");
        slotOcupado1.add(slotNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats1.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado1.add(slotStats1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado1.add(slotImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad1.add(slotOcupado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        slotCiudad2.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad2.setOpaque(false);
        slotCiudad2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot2(evt);
            }
        });
        slotCiudad2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio2.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio2.setText("<Vacio>");
        slotCiudad2.add(slotVacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado2.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre2.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre2.setText("Nombre");
        slotOcupado2.add(slotNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats2.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado2.add(slotStats2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado2.add(slotImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad2.add(slotOcupado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        slotCiudad3.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad3.setOpaque(false);
        slotCiudad3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot3(evt);
            }
        });
        slotCiudad3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio3.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio3.setText("<Vacio>");
        slotCiudad3.add(slotVacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado3.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre3.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre3.setText("Nombre");
        slotOcupado3.add(slotNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats3.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado3.add(slotStats3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado3.add(slotImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad3.add(slotOcupado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        slotCiudad4.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad4.setOpaque(false);
        slotCiudad4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot4(evt);
            }
        });
        slotCiudad4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio4.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio4.setText("<Vacio>");
        slotCiudad4.add(slotVacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado4.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre4.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre4.setText("Nombre");
        slotOcupado4.add(slotNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats4.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado4.add(slotStats4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado4.add(slotImagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad4.add(slotOcupado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        slotCiudad5.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad5.setOpaque(false);
        slotCiudad5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot5(evt);
            }
        });
        slotCiudad5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio5.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio5.setText("<Vacio>");
        slotCiudad5.add(slotVacio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado5.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre5.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre5.setText("Nombre");
        slotOcupado5.add(slotNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats5.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado5.add(slotStats5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado5.add(slotImagen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad5.add(slotOcupado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        slotCiudad6.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad6.setOpaque(false);
        slotCiudad6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot6(evt);
            }
        });
        slotCiudad6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio6.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio6.setText("<Vacio>");
        slotCiudad6.add(slotVacio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado6.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre6.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre6.setText("Nombre");
        slotOcupado6.add(slotNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats6.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado6.add(slotStats6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado6.add(slotImagen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad6.add(slotOcupado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        slotCiudad7.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad7.setOpaque(false);
        slotCiudad7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot7(evt);
            }
        });
        slotCiudad7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio7.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio7.setText("<Vacio>");
        slotCiudad7.add(slotVacio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado7.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre7.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre7.setText("Nombre");
        slotOcupado7.add(slotNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats7.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado7.add(slotStats7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado7.add(slotImagen7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad7.add(slotOcupado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        slotCiudad8.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad8.setOpaque(false);
        slotCiudad8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot8(evt);
            }
        });
        slotCiudad8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio8.setBackground(new java.awt.Color(102, 0, 102));
        slotVacio8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio8.setText("<Vacio>");
        slotCiudad8.add(slotVacio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado8.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre8.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre8.setText("Nombre");
        slotOcupado8.add(slotNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats8.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado8.add(slotStats8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado8.add(slotImagen8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad8.add(slotOcupado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        slotCiudad9.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad9.setOpaque(false);
        slotCiudad9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot9(evt);
            }
        });
        slotCiudad9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio9.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio9.setText("<Vacio>");
        slotCiudad9.add(slotVacio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado9.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre9.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre9.setText("Nombre");
        slotOcupado9.add(slotNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats9.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado9.add(slotStats9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado9.add(slotImagen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad9.add(slotOcupado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        slotCiudad10.setBackground(new java.awt.Color(204, 204, 255));
        slotCiudad10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotCiudad10.setOpaque(false);
        slotCiudad10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot10(evt);
            }
        });
        slotCiudad10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio10.setBackground(new java.awt.Color(204, 204, 255));
        slotVacio10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio10.setText("<Vacio>");
        slotCiudad10.add(slotVacio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado10.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre10.setForeground(new java.awt.Color(255, 255, 255));
        slotNombre10.setText("Nombre");
        slotOcupado10.add(slotNombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));

        slotStats10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotStats10.setForeground(new java.awt.Color(255, 255, 255));
        slotOcupado10.add(slotStats10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 180, 30));
        slotOcupado10.add(slotImagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotCiudad10.add(slotOcupado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotCiudad10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificar.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modificar.setText("Modificar");
        modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarMouseClicked(evt);
            }
        });
        jPanel3.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        fondo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 110, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar1.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        agregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregar1.setText("Agregar");
        agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar1MouseClicked(evt);
            }
        });
        jPanel2.add(agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 110, 20));

        fondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 110, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminar.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar.setText("Eliminar");
        jPanel5.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        fondo.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 110, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminartodo.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        eliminartodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminartodo.setText("Eliminar Todo");
        eliminartodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminartodoMouseClicked(evt);
            }
        });
        jPanel4.add(eliminartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        fondo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 110, 20));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        personajes.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        personajes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personajes.setText("Personajes");
        personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                personajesMouseClicked(evt);
            }
        });
        jPanel6.add(personajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        fondo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 110, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar.setText("Regresar");
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        jPanel7.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        fondo.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 110, 20));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("Salir");
        Salir.setToolTipText("");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 110, 20));

        fondociudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/gestionCiudades.png"))); // NOI18N
        fondo.add(fondociudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickSlot1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot1
        slotCiudad1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad1;
        slotSeleccionadoNum = 0;
    }//GEN-LAST:event_clickSlot1

    private void clickSlot2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot2
        slotCiudad2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad2;
        slotSeleccionadoNum = 1;
    }//GEN-LAST:event_clickSlot2

    private void clickSlot3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot3
        slotCiudad3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad3;
        slotSeleccionadoNum = 2;
    }//GEN-LAST:event_clickSlot3

    private void clickSlot4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot4
        slotCiudad4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad4;
        slotSeleccionadoNum = 3;
    }//GEN-LAST:event_clickSlot4

    private void clickSlot5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot5
        slotCiudad5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad5;
        slotSeleccionadoNum = 4;
    }//GEN-LAST:event_clickSlot5

    private void clickSlot6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot6
        slotCiudad6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad6;
        slotSeleccionadoNum = 5;
    }//GEN-LAST:event_clickSlot6

    private void clickSlot7(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot7
        slotCiudad7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad7;
        slotSeleccionadoNum = 6;
    }//GEN-LAST:event_clickSlot7

    private void clickSlot8(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot8
        slotCiudad8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad8;
        slotSeleccionadoNum = 7;
    }//GEN-LAST:event_clickSlot8

    private void clickSlot9(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot9
        slotCiudad9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad9;
        slotSeleccionadoNum = 8;
    }//GEN-LAST:event_clickSlot9

    private void clickSlot10(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot10
        slotCiudad10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotCiudad10;
        slotSeleccionadoNum = 9;
    }//GEN-LAST:event_clickSlot10

    private void agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar1MouseClicked
        B_GestionCiudadesAux nf = new B_GestionCiudadesAux('a');
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregar1MouseClicked

    private void modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarMouseClicked
        if (slotSeleccionadoNum >= 0 ){
            B_GestionCiudadesAux gestionCiudadesAux = new B_GestionCiudadesAux('m');
            gestionCiudadesAux.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_modificarMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
         if (slotSeleccionadoNum >= 0 ){
            ManejoJSON.borrarJSON(slotSeleccionadoNum, Ciudad.RUTA);
            vaciarSlots();
            actualizarSlots();
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void eliminartodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminartodoMouseClicked
        borrarTodoJSON(Ciudad.RUTA);
        vaciarSlots();
        actualizarSlots();
    }//GEN-LAST:event_eliminartodoMouseClicked

    private void personajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_personajesMouseClicked
        if (slotSeleccionadoNum >= 0 ){
            C_GestionHeroes.ciudad = ciudades.get(slotSeleccionadoNum);
            C_GestionHeroes gestionHeroes = new C_GestionHeroes();
            gestionHeroes.setVisible(true);
            this.dispose();
        }  
    }//GEN-LAST:event_personajesMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        A_MenuServidor nf = new A_MenuServidor();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new B_GestionCiudades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel agregar1;
    private javax.swing.JLabel eliminar;
    private javax.swing.JLabel eliminartodo;
    private java.awt.Panel fondo;
    private javax.swing.JLabel fondociudad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel modificar;
    private javax.swing.JLabel personajes;
    private javax.swing.JLabel regresar;
    private javax.swing.JPanel slotCiudad1;
    private javax.swing.JPanel slotCiudad10;
    private javax.swing.JPanel slotCiudad2;
    private javax.swing.JPanel slotCiudad3;
    private javax.swing.JPanel slotCiudad4;
    private javax.swing.JPanel slotCiudad5;
    private javax.swing.JPanel slotCiudad6;
    private javax.swing.JPanel slotCiudad7;
    private javax.swing.JPanel slotCiudad8;
    private javax.swing.JPanel slotCiudad9;
    private javax.swing.JLabel slotImagen1;
    private javax.swing.JLabel slotImagen10;
    private javax.swing.JLabel slotImagen2;
    private javax.swing.JLabel slotImagen3;
    private javax.swing.JLabel slotImagen4;
    private javax.swing.JLabel slotImagen5;
    private javax.swing.JLabel slotImagen6;
    private javax.swing.JLabel slotImagen7;
    private javax.swing.JLabel slotImagen8;
    private javax.swing.JLabel slotImagen9;
    private javax.swing.JLabel slotNombre1;
    private javax.swing.JLabel slotNombre10;
    private javax.swing.JLabel slotNombre2;
    private javax.swing.JLabel slotNombre3;
    private javax.swing.JLabel slotNombre4;
    private javax.swing.JLabel slotNombre5;
    private javax.swing.JLabel slotNombre6;
    private javax.swing.JLabel slotNombre7;
    private javax.swing.JLabel slotNombre8;
    private javax.swing.JLabel slotNombre9;
    private javax.swing.JPanel slotOcupado1;
    private javax.swing.JPanel slotOcupado10;
    private javax.swing.JPanel slotOcupado2;
    private javax.swing.JPanel slotOcupado3;
    private javax.swing.JPanel slotOcupado4;
    private javax.swing.JPanel slotOcupado5;
    private javax.swing.JPanel slotOcupado6;
    private javax.swing.JPanel slotOcupado7;
    private javax.swing.JPanel slotOcupado8;
    private javax.swing.JPanel slotOcupado9;
    private javax.swing.JLabel slotStats1;
    private javax.swing.JLabel slotStats10;
    private javax.swing.JLabel slotStats2;
    private javax.swing.JLabel slotStats3;
    private javax.swing.JLabel slotStats4;
    private javax.swing.JLabel slotStats5;
    private javax.swing.JLabel slotStats6;
    private javax.swing.JLabel slotStats7;
    private javax.swing.JLabel slotStats8;
    private javax.swing.JLabel slotStats9;
    private javax.swing.JLabel slotVacio1;
    private javax.swing.JLabel slotVacio10;
    private javax.swing.JLabel slotVacio2;
    private javax.swing.JLabel slotVacio3;
    private javax.swing.JLabel slotVacio4;
    private javax.swing.JLabel slotVacio5;
    private javax.swing.JLabel slotVacio6;
    private javax.swing.JLabel slotVacio7;
    private javax.swing.JLabel slotVacio8;
    private javax.swing.JLabel slotVacio9;
    // End of variables declaration//GEN-END:variables

    private void actualizarSlots() {
        ciudades = ManejoJSON.leerJSON(Ciudad.RUTA, Ciudad.class);
        ImageIcon mIcono = null;
        for (int i = 0; i < ciudades.size(); i++){
            slotsOcupados.get(i).setVisible(true);
            slotsOcupados.get(i).setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));  
            slotsVacios.get(i).setVisible(false);
            
            //Nombre
            nombres.get(i).setText(ciudades.get(i).getCiudad());
            
            //Estadisticas
            Ciudad ciudad = ciudades.get(i);
            String tInfo = "Pais: " + ciudad.getPais() + " Estado: " + ciudad.getEstado();
            stats.get(i).setText(tInfo);
                      
            // Imagen Fondo
            switch (ciudades.get(i).getEscenario()) {
                case BOSQUE -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/BosqueLowerThird.png")));
                case CIUDAD -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/CiudadLowerThird.png")));
                case DESIERTO -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/DesiertoLowerThird.png")));
                case MONTAÑA -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/MontañaLowerThird.png")));
                default -> {
                }
            }
            
        
        }
    }

    private void vaciarSlots() {
        slotOcupado1.setVisible(false);
        slotOcupado2.setVisible(false);
        slotOcupado3.setVisible(false);
        slotOcupado4.setVisible(false);
        slotOcupado5.setVisible(false);
        slotOcupado6.setVisible(false);
        slotOcupado7.setVisible(false);
        slotOcupado8.setVisible(false);
        slotOcupado9.setVisible(false);
        slotOcupado10.setVisible(false);
        slotVacio1.setVisible(true);
        slotVacio2.setVisible(true);
        slotVacio3.setVisible(true);
        slotVacio4.setVisible(true);
        slotVacio5.setVisible(true);
        slotVacio6.setVisible(true);
        slotVacio7.setVisible(true);
        slotVacio8.setVisible(true);
        slotVacio9.setVisible(true);
        slotVacio10.setVisible(true);
        
    }

    private void llenarListaObjetos() {
        slotsOcupados.add(slotOcupado1);
        slotsOcupados.add(slotOcupado2);
        slotsOcupados.add(slotOcupado3);
        slotsOcupados.add(slotOcupado4);
        slotsOcupados.add(slotOcupado5);
        slotsOcupados.add(slotOcupado6);
        slotsOcupados.add(slotOcupado7);
        slotsOcupados.add(slotOcupado8);
        slotsOcupados.add(slotOcupado9);
        slotsOcupados.add(slotOcupado10);
        
        slotsVacios.add(slotVacio1);
        slotsVacios.add(slotVacio2);
        slotsVacios.add(slotVacio3);
        slotsVacios.add(slotVacio4);
        slotsVacios.add(slotVacio5);
        slotsVacios.add(slotVacio6);
        slotsVacios.add(slotVacio7);
        slotsVacios.add(slotVacio8);
        slotsVacios.add(slotVacio9);
        slotsVacios.add(slotVacio10);
        
        nombres.add(slotNombre1);
        nombres.add(slotNombre2);
        nombres.add(slotNombre3);
        nombres.add(slotNombre4);
        nombres.add(slotNombre5);
        nombres.add(slotNombre6);
        nombres.add(slotNombre7);
        nombres.add(slotNombre8);
        nombres.add(slotNombre9);
        nombres.add(slotNombre10);
     
        stats.add(slotStats1);
        stats.add(slotStats2);
        stats.add(slotStats3);
        stats.add(slotStats4);
        stats.add(slotStats5);
        stats.add(slotStats6);
        stats.add(slotStats7);
        stats.add(slotStats8);
        stats.add(slotStats9);
        stats.add(slotStats10);
        
        imagenes.add(slotImagen1);
        imagenes.add(slotImagen2);
        imagenes.add(slotImagen3);
        imagenes.add(slotImagen4);
        imagenes.add(slotImagen5);
        imagenes.add(slotImagen6);
        imagenes.add(slotImagen7);
        imagenes.add(slotImagen8);
        imagenes.add(slotImagen9);
        imagenes.add(slotImagen10);
    }
}
