package gui;

import aplicacion.ManejoJSON;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import logicadenegocios.Ciudad;
import logicadenegocios.Escenario;

/**
 *
 * @author emifu
 */
public class B_GestionCiudadesAux extends javax.swing.JFrame {
    
    public char modo;
    /**
     * Creates new form I_MenuInicio
     * @param modo
     */
    public B_GestionCiudadesAux(char modo) {
        this.modo = modo;
        initComponents();
        this.setLocationRelativeTo(null);
        inputEscenario.setModel(new DefaultComboBoxModel<>(Escenario.values())); 
        if (modo == 'a'){
            labelTitulo.setText("Nueva Ciudad");
        } else if (modo == 'm'){
            labelTitulo.setText("Modificar Ciudad");
            llenarInputs();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        inputPais = new javax.swing.JTextField();
        labelPais = new javax.swing.JLabel();
        inputEstado = new javax.swing.JTextField();
        labelEstado = new javax.swing.JLabel();
        labelEscenario = new javax.swing.JLabel();
        inputCiudad = new javax.swing.JTextField();
        labelCiudad = new javax.swing.JLabel();
        inputEscenario = new javax.swing.JComboBox<>();
        labelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Confirmar = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        Atras = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setPreferredSize(new java.awt.Dimension(900, 500));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputPais.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        inputPais.setForeground(new java.awt.Color(153, 153, 153));
        inputPais.setText("Nombre de país");
        inputPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPaisActionPerformed(evt);
            }
        });
        panel1.add(inputPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, 30));

        labelPais.setFont(new java.awt.Font("Comic Book", 0, 24)); // NOI18N
        labelPais.setForeground(new java.awt.Color(255, 255, 255));
        labelPais.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPais.setText("Pais");
        panel1.add(labelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 60, 30));

        inputEstado.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        inputEstado.setForeground(new java.awt.Color(153, 153, 153));
        inputEstado.setText("Nombre de estado");
        inputEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEstadoActionPerformed(evt);
            }
        });
        panel1.add(inputEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 170, 30));

        labelEstado.setFont(new java.awt.Font("Comic Book", 0, 24)); // NOI18N
        labelEstado.setForeground(new java.awt.Color(255, 255, 255));
        labelEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEstado.setText("Estado");
        panel1.add(labelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 100, 30));

        labelEscenario.setFont(new java.awt.Font("Comic Book", 0, 24)); // NOI18N
        labelEscenario.setForeground(new java.awt.Color(255, 255, 255));
        labelEscenario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEscenario.setText("Escenario");
        panel1.add(labelEscenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 140, 30));

        inputCiudad.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        inputCiudad.setForeground(new java.awt.Color(153, 153, 153));
        inputCiudad.setText("Nombre de ciudad");
        inputCiudad.setDoubleBuffered(true);
        inputCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCiudadActionPerformed(evt);
            }
        });
        panel1.add(inputCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 170, 30));

        labelCiudad.setFont(new java.awt.Font("Comic Book", 0, 24)); // NOI18N
        labelCiudad.setForeground(new java.awt.Color(255, 255, 255));
        labelCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCiudad.setText("Ciudad");
        panel1.add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 90, 30));

        inputEscenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEscenarioActionPerformed(evt);
            }
        });
        panel1.add(inputEscenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 170, 30));

        labelTitulo.setFont(new java.awt.Font("Comic Book", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Gestion Ciudades");
        panel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 350, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Confirmar.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        Confirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Confirmar.setText("Confirmar");
        Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmarMouseClicked(evt);
            }
        });
        jPanel1.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 170, 30));

        Salir.setFont(new java.awt.Font("Comic Book", 0, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 255, 255));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        panel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 70, 30));

        Atras.setFont(new java.awt.Font("Comic Book", 0, 18)); // NOI18N
        Atras.setForeground(new java.awt.Color(255, 255, 255));
        Atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Atras.setText("Atrás");
        Atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtrasMouseClicked(evt);
            }
        });
        panel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 70, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/gestionCiudades.png"))); // NOI18N
        fondo.setToolTipText("");
        panel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPaisActionPerformed

    private void inputEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEstadoActionPerformed

    }//GEN-LAST:event_inputEstadoActionPerformed

    private void inputCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCiudadActionPerformed

    private void inputEscenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEscenarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEscenarioActionPerformed

    private void ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarMouseClicked
       if(inputPais.getText().trim().isEmpty() | inputPais.getText().equals("Nombre de país")){
            JOptionPane.showMessageDialog(null, "Rellene el país", "Error", JOptionPane.WARNING_MESSAGE);      
        }else if (inputCiudad.getText().trim().isEmpty() | inputCiudad.getText().equals("Nombre de ciudad")){
            JOptionPane.showMessageDialog(null, "Rellene la ciudad", "Error", JOptionPane.WARNING_MESSAGE);
        }else if (inputEstado.getText().trim().isEmpty() | inputEstado.getText().equals("Nombre de estado")){
            JOptionPane.showMessageDialog(null, "Rellene el estado", "Error", JOptionPane.WARNING_MESSAGE); 
        }else{
            Ciudad ciudad = getInformacion();
            if (modo == 'a'){
                ManejoJSON.guardarJSON(ciudad, Ciudad.RUTA);
            } else if (modo == 'm'){
                ManejoJSON.modificarJSON(ciudad, B_GestionCiudades.slotSeleccionadoNum, Ciudad.RUTA);
            }
            B_GestionCiudades gestionCiudades = new B_GestionCiudades();
            gestionCiudades.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ConfirmarMouseClicked

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void AtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasMouseClicked
        B_GestionCiudades nf = new B_GestionCiudades();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudadesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudadesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudadesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_GestionCiudadesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            char modo;
            @Override
            public void run() {
                new B_GestionCiudadesAux(modo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atras;
    private javax.swing.JLabel Confirmar;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField inputCiudad;
    private javax.swing.JComboBox<Escenario> inputEscenario;
    private javax.swing.JTextField inputEstado;
    private javax.swing.JTextField inputPais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelEscenario;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelPais;
    private javax.swing.JLabel labelTitulo;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
    private Ciudad getInformacion() {
        String nombre = inputCiudad.getText();
        String pais = inputPais.getText();
        String estado = inputEstado.getText();
        Escenario escenario = (Escenario) inputEscenario.getSelectedItem();
        Ciudad ciudad = new Ciudad(pais, estado, nombre, escenario);
        return ciudad;
        
    }
    
    private void llenarInputs() {
        ArrayList lista = ManejoJSON.leerJSON(Ciudad.RUTA, Ciudad.class);
        Ciudad ciudad = (Ciudad) lista.get(B_GestionCiudades.slotSeleccionadoNum);
        inputCiudad.setText(ciudad.getCiudad());
        inputPais.setText(ciudad.getPais());
        inputEstado.setText(ciudad.getEstado());
        inputEscenario.setSelectedItem(ciudad.getEscenario());
    }
}
