/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.ManejoJSON;
import gui.C_EliminarUsuario;
import javax.swing.JOptionPane;
import logicadenegocios.Usuario;

/**
 *
 * @author Ginge
 */
public class B_RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form B_RegistroUsuario
     */
    public B_RegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistroUsuario = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        inputApellidos = new javax.swing.JTextField();
        inputCorreo = new javax.swing.JTextField();
        inputNombre = new javax.swing.JTextField();
        inputUsuario = new javax.swing.JTextField();
        inputContraseña = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        labelRegistroUsuario = new javax.swing.JLabel();
        panelAñadir = new javax.swing.JPanel();
        labelAñadir = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        labelEditar = new javax.swing.JLabel();
        panelEliminar = new javax.swing.JPanel();
        labelEliminar = new javax.swing.JLabel();
        panelAtras = new javax.swing.JPanel();
        labelAtras = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        labelSalir = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistroUsuario.setBackground(new java.awt.Color(255, 255, 255, 220));
        panelRegistroUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panelRegistroUsuario.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelNombre.setText("Nombre");
        panelRegistroUsuario.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, -1));

        labelApellidos.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelApellidos.setText("Apellidos");
        panelRegistroUsuario.add(labelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 90, -1));

        labelUsuario.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelUsuario.setText("Nombre de Usuario");
        panelRegistroUsuario.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 180, -1));

        labelCorreo.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelCorreo.setText("Correo");
        panelRegistroUsuario.add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 90, -1));

        labelContraseña.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelContraseña.setText("Contraseña");
        panelRegistroUsuario.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 120, -1));

        inputApellidos.setForeground(new java.awt.Color(153, 153, 153));
        inputApellidos.setText("Ingrese ambos apellidos");
        inputApellidos.setBorder(null);
        inputApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputApellidosFocusLost(evt);
            }
        });
        inputApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputApellidosMouseClicked(evt);
            }
        });
        panelRegistroUsuario.add(inputApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        inputCorreo.setForeground(new java.awt.Color(153, 153, 153));
        inputCorreo.setText("Ingrese correo");
        inputCorreo.setBorder(null);
        inputCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputCorreoFocusLost(evt);
            }
        });
        inputCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputCorreoMouseClicked(evt);
            }
        });
        panelRegistroUsuario.add(inputCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 140, -1));

        inputNombre.setForeground(new java.awt.Color(153, 153, 153));
        inputNombre.setText("Ingrese nombre");
        inputNombre.setBorder(null);
        inputNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombreFocusLost(evt);
            }
        });
        inputNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputNombreMouseClicked(evt);
            }
        });
        panelRegistroUsuario.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 140, -1));

        inputUsuario.setBackground(new java.awt.Color(242, 242, 242));
        inputUsuario.setForeground(new java.awt.Color(153, 153, 153));
        inputUsuario.setText("Ingrese usuario válido");
        inputUsuario.setBorder(null);
        inputUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputUsuarioFocusLost(evt);
            }
        });
        inputUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputUsuarioMouseClicked(evt);
            }
        });
        panelRegistroUsuario.add(inputUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, -1));

        inputContraseña.setForeground(new java.awt.Color(153, 153, 153));
        inputContraseña.setText("jPasswordField1");
        inputContraseña.setBorder(null);
        inputContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputContraseñaFocusLost(evt);
            }
        });
        inputContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputContraseñaMouseClicked(evt);
            }
        });
        panelRegistroUsuario.add(inputContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 130, -1));

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        panelRegistroUsuario.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, -1));

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        panelRegistroUsuario.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 130, 10));

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        panelRegistroUsuario.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, 20));

        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        panelRegistroUsuario.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 130, 10));

        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        panelRegistroUsuario.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, 10));

        labelRegistroUsuario.setFont(new java.awt.Font("Comic Book", 1, 24)); // NOI18N
        labelRegistroUsuario.setText("Registro de Usuario");
        panelRegistroUsuario.add(labelRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, -1));

        panelAñadir.setBackground(new java.awt.Color(255, 255, 255));

        labelAñadir.setBackground(new java.awt.Color(255, 255, 255));
        labelAñadir.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelAñadir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAñadir.setText("Agregar");
        labelAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickAñadir(evt);
            }
        });

        javax.swing.GroupLayout panelAñadirLayout = new javax.swing.GroupLayout(panelAñadir);
        panelAñadir.setLayout(panelAñadirLayout);
        panelAñadirLayout.setHorizontalGroup(
            panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAñadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAñadirLayout.setVerticalGroup(
            panelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAñadirLayout.createSequentialGroup()
                .addComponent(labelAñadir)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelRegistroUsuario.add(panelAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 20));

        panelEditar.setBackground(new java.awt.Color(255, 255, 255));

        labelEditar.setBackground(new java.awt.Color(255, 255, 255));
        labelEditar.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEditar.setText("Editar");

        javax.swing.GroupLayout panelEditarLayout = new javax.swing.GroupLayout(panelEditar);
        panelEditar.setLayout(panelEditarLayout);
        panelEditarLayout.setHorizontalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelEditarLayout.setVerticalGroup(
            panelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditarLayout.createSequentialGroup()
                .addComponent(labelEditar)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelRegistroUsuario.add(panelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, 20));

        panelEliminar.setBackground(new java.awt.Color(255, 255, 255));

        labelEliminar.setFont(new java.awt.Font("Comic Book", 0, 14)); // NOI18N
        labelEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEliminar.setText("Eliminar");
        labelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEliminarLayout = new javax.swing.GroupLayout(panelEliminar);
        panelEliminar.setLayout(panelEliminarLayout);
        panelEliminarLayout.setHorizontalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEliminarLayout.setVerticalGroup(
            panelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEliminarLayout.createSequentialGroup()
                .addComponent(labelEliminar)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        panelRegistroUsuario.add(panelEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, 20));

        getContentPane().add(panelRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 500, 280));

        panelAtras.setBackground(new java.awt.Color(51, 51, 51));
        panelAtras.setForeground(new java.awt.Color(255, 255, 255));

        labelAtras.setFont(new java.awt.Font("Comic Book", 1, 18)); // NOI18N
        labelAtras.setForeground(new java.awt.Color(255, 255, 255));
        labelAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAtras.setText("Atras");
        labelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAtrasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelAtrasLayout = new javax.swing.GroupLayout(panelAtras);
        panelAtras.setLayout(panelAtrasLayout);
        panelAtrasLayout.setHorizontalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        panelAtrasLayout.setVerticalGroup(
            panelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelAtras, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panelAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 70, 30));

        panelSalir.setBackground(new java.awt.Color(51, 51, 51));
        panelSalir.setForeground(new java.awt.Color(255, 255, 255));
        panelSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelSalir.setFont(new java.awt.Font("Comic Book", 1, 18)); // NOI18N
        labelSalir.setForeground(new java.awt.Color(255, 255, 255));
        labelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSalir.setText("Salir");
        labelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSalirMouseClicked(evt);
            }
        });
        panelSalir.add(labelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        getContentPane().add(panelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 70, 30));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/registroUsarios.png"))); // NOI18N
        labelFondo.setText("jLabel1");
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelSalirMouseClicked

    private void labelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAtrasMouseClicked
        A_ControlAcceso newframe = new A_ControlAcceso();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelAtrasMouseClicked

    private void labelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEliminarMouseClicked
        C_EliminarUsuario nf = new C_EliminarUsuario();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelEliminarMouseClicked

    private void clickAñadir(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickAñadir
        if(inputNombre.getText().trim().isEmpty() | inputNombre.getText().equals("Ingrese nombre")){
            JOptionPane.showMessageDialog(null, "Rellene el nombre", "Error", JOptionPane.WARNING_MESSAGE);      
        }else if (inputApellidos.getText().trim().isEmpty() | inputApellidos.getText().equals("Ingrese ambos apellidos")){
            JOptionPane.showMessageDialog(null, "Rellene los apellidos", "Error", JOptionPane.WARNING_MESSAGE);
        }else if (inputCorreo.getText().trim().isEmpty() | inputCorreo.getText().equals("Ingrese correo")){
            JOptionPane.showMessageDialog(null, "Rellene el correo", "Error", JOptionPane.WARNING_MESSAGE); 
        }else if (inputContraseña.getPassword().length == 0 | inputContraseña.getPassword().equals("jPasswordField1")){
            JOptionPane.showMessageDialog(null, "Rellene la contraseña", "Error", JOptionPane.WARNING_MESSAGE);
        }else if (inputUsuario.getText().trim().isEmpty() | inputUsuario.getText().equals("Ingrese usuario válido")){
            JOptionPane.showMessageDialog(null, "Rellene el nombre de usuario", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            Usuario usuario = getInformacion();
            ManejoJSON.guardarJSON(usuario, Usuario.RUTA);
            limpiarInputs();
            JOptionPane.showMessageDialog(null, "Usuario agregado");
        }
    }//GEN-LAST:event_clickAñadir

    private void inputNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusLost
        inputNombre.setText("Ingrese nombre");
    }//GEN-LAST:event_inputNombreFocusLost

    private void inputApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputApellidosFocusLost
        inputApellidos.setText("Ingrese ambos apellidos");
    }//GEN-LAST:event_inputApellidosFocusLost

    private void inputCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputCorreoFocusLost
        inputCorreo.setText("Ingrese correo válido");
    }//GEN-LAST:event_inputCorreoFocusLost

    private void inputContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputContraseñaFocusLost
        inputContraseña.setText("Contraseña");
    }//GEN-LAST:event_inputContraseñaFocusLost

    private void inputUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUsuarioFocusLost
        inputUsuario.setText("Ingrese usuario válido");
    }//GEN-LAST:event_inputUsuarioFocusLost

    private void inputNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputNombreMouseClicked
        inputNombre.setText("");
    }//GEN-LAST:event_inputNombreMouseClicked

    private void inputApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputApellidosMouseClicked
        inputApellidos.setText("");
    }//GEN-LAST:event_inputApellidosMouseClicked

    private void inputCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCorreoMouseClicked
        inputCorreo.setText("");
    }//GEN-LAST:event_inputCorreoMouseClicked

    private void inputContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputContraseñaMouseClicked
        inputContraseña.setText("");
    }//GEN-LAST:event_inputContraseñaMouseClicked

    private void inputUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsuarioMouseClicked
        inputUsuario.setText("");
    }//GEN-LAST:event_inputUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_RegistroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputApellidos;
    private javax.swing.JPasswordField inputContraseña;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelAtras;
    private javax.swing.JLabel labelAñadir;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelEditar;
    private javax.swing.JLabel labelEliminar;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRegistroUsuario;
    private javax.swing.JLabel labelSalir;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelAtras;
    private javax.swing.JPanel panelAñadir;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelEliminar;
    private javax.swing.JPanel panelRegistroUsuario;
    private javax.swing.JPanel panelSalir;
    // End of variables declaration//GEN-END:variables

    private Usuario getInformacion() {
        String nombre = inputNombre.getText();
        String apellidos = inputApellidos.getText();
        String correo = inputCorreo.getText();
        char[] contraseña = inputContraseña.getPassword();
        String nombreUsuario = inputUsuario.getText();
        Usuario usuario= new Usuario(nombre, apellidos, nombreUsuario, correo, contraseña);
        return usuario;
    }

    private void limpiarInputs() {
        inputNombre.setText("Ingrese nombre");
        inputApellidos.setText("Ingrese ambos apellidos");
        inputCorreo.setText("Ingrese correo");
        inputContraseña.setText("jPasswordField1");
        inputUsuario.setText("Ingrese usuario valido");
    }
}
