package gui;

import logicadenegocios.TipoDePersonaje;
import logicadenegocios.Poder;
import logicadenegocios.TipoDeClase;
import logicadenegocios.DatosPersonales;
import logicadenegocios.DatosHeroe;
import aplicacion.ManejoJSON;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import logicadenegocios.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ginge
 */
public class C_GestionHeroesAux extends javax.swing.JFrame {
    public char modo;
    private Imagen imagen;
    /**
     * Creates new form ll_GestionHeroes
     * @param modo
     */
    public C_GestionHeroesAux(char modo) {
        this.modo = modo;
        initComponents();
        inputTipoDeClase.setModel(new DefaultComboBoxModel<>(TipoDeClase.values()));
        inputTipoDePersonaje.setModel(new DefaultComboBoxModel<>(TipoDePersonaje.values()));  
        if (modo == 'a'){
            labelTitulo.setText("Nuevo Personaje");
        } else if (modo == 'm'){
            labelTitulo.setText("Modificar Personaje");
            llenarInputs();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        inputFranquicia = new javax.swing.JComboBox<>();
        labelFranquicia = new javax.swing.JLabel();
        labelTipoDePersonaje = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        labelCiudad = new javax.swing.JLabel();
        sliderFuerza = new javax.swing.JSlider();
        sliderVelocidad = new javax.swing.JSlider();
        sliderInteligencia = new javax.swing.JSlider();
        sliderVida = new javax.swing.JSlider();
        labelFuerza = new javax.swing.JLabel();
        labelVelocidad = new javax.swing.JLabel();
        labelInteligencia = new javax.swing.JLabel();
        labelPoderNum = new javax.swing.JLabel();
        inputFecha = new com.toedter.calendar.JDateChooser();
        inputFoto = new javax.swing.JLabel();
        imagen = new Imagen("/recursos/defecto/foto.png");
        botonCorrecto = new javax.swing.JButton();
        botonAgregarFoto = new javax.swing.JButton();
        inputCiudad = new javax.swing.JTextField();
        labelPseudonimo = new javax.swing.JLabel();
        inputPseudonimo = new javax.swing.JTextField();
        inputTipoDePersonaje = new javax.swing.JComboBox<>();
        labelTipoDeClase = new javax.swing.JLabel();
        inputTipoDeClase = new javax.swing.JComboBox<>();
        labelRecursosEco1 = new javax.swing.JLabel();
        sliderRecursosEco = new javax.swing.JSlider();
        labelVelocidadNum = new javax.swing.JLabel();
        labelVida = new javax.swing.JLabel();
        labelVidaNum = new javax.swing.JLabel();
        labelRecursosEcoNum = new javax.swing.JLabel();
        labelInteligenciaNum = new javax.swing.JLabel();
        labelFuerzaNum = new javax.swing.JLabel();
        labelPoderText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Nuevo Personaje");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 31, 910, 30));

        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombre.setText("Nombre Completo");
        getContentPane().add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 100, 30));

        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFecha.setText("Fecha de nacimiento");
        getContentPane().add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 110, 30));

        inputFranquicia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marvel", "DC", "Otro" }));
        inputFranquicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFranquiciaActionPerformed(evt);
            }
        });
        getContentPane().add(inputFranquicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 130, -1));

        labelFranquicia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFranquicia.setText("Franquicia");
        getContentPane().add(labelFranquicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 60, 30));

        labelTipoDePersonaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTipoDePersonaje.setText("Tipo de Personaje");
        getContentPane().add(labelTipoDePersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 110, 30));
        getContentPane().add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 130, -1));

        labelCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCiudad.setText("Ciudad");
        getContentPane().add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 100, 30));

        sliderFuerza.setMajorTickSpacing(25);
        sliderFuerza.setPaintTicks(true);
        sliderFuerza.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderFuerzaStateChanged(evt);
            }
        });
        getContentPane().add(sliderFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        sliderVelocidad.setMajorTickSpacing(25);
        sliderVelocidad.setPaintTicks(true);
        sliderVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVelocidadStateChanged(evt);
            }
        });
        getContentPane().add(sliderVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, -1));

        sliderInteligencia.setMajorTickSpacing(25);
        sliderInteligencia.setPaintTicks(true);
        sliderInteligencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderInteligenciaStateChanged(evt);
            }
        });
        getContentPane().add(sliderInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        sliderVida.setMajorTickSpacing(25);
        sliderVida.setPaintTicks(true);
        sliderVida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVidaStateChanged(evt);
            }
        });
        getContentPane().add(sliderVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        labelFuerza.setText("Fuerza");
        getContentPane().add(labelFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        labelVelocidad.setText("Velocidad");
        getContentPane().add(labelVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, -1, -1));

        labelInteligencia.setText("Inteligencia");
        getContentPane().add(labelInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        labelPoderNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPoderNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPoderNum.setText("50");
        labelPoderNum.setToolTipText("");
        labelPoderNum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(labelPoderNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 40, 40));
        getContentPane().add(inputFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 130, -1));

        inputFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/defecto/foto.png"))); // NOI18N
        getContentPane().add(inputFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        botonCorrecto.setText("Confirmar");
        botonCorrecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCorrectoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 120, -1));

        botonAgregarFoto.setText("Agregar Foto");
        botonAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarFotoActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 120, -1));

        inputCiudad.setEditable(false);
        inputCiudad.setText(gui.C_GestionHeroes.ciudad.getCiudad());
        getContentPane().add(inputCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 130, -1));

        labelPseudonimo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPseudonimo.setText("Pseudonimo");
        getContentPane().add(labelPseudonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, 30));
        getContentPane().add(inputPseudonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 131, -1));

        getContentPane().add(inputTipoDePersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, -1));

        labelTipoDeClase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTipoDeClase.setText("Tipo de Clase");
        getContentPane().add(labelTipoDeClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 90, 30));

        inputTipoDeClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipoDeClaseActionPerformed(evt);
            }
        });
        getContentPane().add(inputTipoDeClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 130, -1));

        labelRecursosEco1.setText("Recursos Economicos");
        getContentPane().add(labelRecursosEco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, 20));

        sliderRecursosEco.setMajorTickSpacing(25);
        sliderRecursosEco.setPaintTicks(true);
        sliderRecursosEco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRecursosEcoStateChanged(evt);
            }
        });
        getContentPane().add(sliderRecursosEco, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, -1));

        labelVelocidadNum.setText("50");
        getContentPane().add(labelVelocidadNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, -1, 20));

        labelVida.setText("Vida");
        getContentPane().add(labelVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, 20));

        labelVidaNum.setText("50");
        getContentPane().add(labelVidaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, -1, 20));

        labelRecursosEcoNum.setText("50");
        getContentPane().add(labelRecursosEcoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, 20));

        labelInteligenciaNum.setText("50");
        getContentPane().add(labelInteligenciaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, 20));

        labelFuerzaNum.setText("50");
        getContentPane().add(labelFuerzaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, 20));

        labelPoderText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPoderText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPoderText.setText("PODER");
        labelPoderText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(labelPoderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFranquiciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFranquiciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFranquiciaActionPerformed

    private void botonCorrectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCorrectoActionPerformed
        Personaje personaje = getInformacion();  
        if (modo == 'a'){
            ManejoJSON.guardarJSON(personaje, Personaje.RUTA);
        } else if (modo == 'm'){
            ManejoJSON.modificarJSON(personaje, C_GestionHeroes.slotSeleccionadoNum, Personaje.RUTA);
        }
        C_GestionHeroes gestionHeroes = new C_GestionHeroes();
        gestionHeroes.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonCorrectoActionPerformed

    private void botonAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarFotoActionPerformed
        String Ruta = "";
        JFileChooser jFileChooser = new JFileChooser("C:\\Users\\emifu\\Desktop\\ProyectoII_Marvel_v3\\src\\recursos");
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JGP, PNG & GIF", "jpg", "png", "gif");
        jFileChooser.setFileFilter(filtrado);
        
        
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            Ruta = jFileChooser.getSelectedFile().getPath();
            imagen = new Imagen(Ruta);
            Image mImagen = new ImageIcon(Ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(inputFoto.getWidth(), inputFoto.getHeight(), Image.SCALE_SMOOTH));
            inputFoto.setIcon(mIcono); 
            
        }
    }//GEN-LAST:event_botonAgregarFotoActionPerformed

    private void inputTipoDeClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipoDeClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoDeClaseActionPerformed

    private void sliderFuerzaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderFuerzaStateChanged
        labelFuerzaNum.setText( "" + sliderFuerza.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderFuerzaStateChanged

    private void sliderRecursosEcoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRecursosEcoStateChanged
        labelRecursosEcoNum.setText( "" + sliderRecursosEco.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderRecursosEcoStateChanged

    private void sliderVidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVidaStateChanged
        labelVidaNum.setText( "" + sliderVida.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderVidaStateChanged

    private void sliderInteligenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderInteligenciaStateChanged
        labelInteligenciaNum.setText( "" + sliderInteligencia.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderInteligenciaStateChanged

    private void sliderVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVelocidadStateChanged
        labelVelocidadNum.setText( "" + sliderVelocidad.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderVelocidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private char modo;
            @Override
            public void run() {
                new C_GestionHeroesAux(modo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarFoto;
    private javax.swing.JButton botonCorrecto;
    private javax.swing.JTextField inputCiudad;
    private com.toedter.calendar.JDateChooser inputFecha;
    public static javax.swing.JLabel inputFoto;
    private javax.swing.JComboBox<String> inputFranquicia;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputPseudonimo;
    private javax.swing.JComboBox<TipoDeClase> inputTipoDeClase;
    private javax.swing.JComboBox<TipoDePersonaje> inputTipoDePersonaje;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFranquicia;
    private javax.swing.JLabel labelFuerza;
    private javax.swing.JLabel labelFuerzaNum;
    private javax.swing.JLabel labelInteligencia;
    private javax.swing.JLabel labelInteligenciaNum;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPoderNum;
    private javax.swing.JLabel labelPoderText;
    private javax.swing.JLabel labelPseudonimo;
    private javax.swing.JLabel labelRecursosEco1;
    private javax.swing.JLabel labelRecursosEcoNum;
    private javax.swing.JLabel labelTipoDeClase;
    private javax.swing.JLabel labelTipoDePersonaje;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVelocidad;
    private javax.swing.JLabel labelVelocidadNum;
    private javax.swing.JLabel labelVida;
    private javax.swing.JLabel labelVidaNum;
    private javax.swing.JSlider sliderFuerza;
    private javax.swing.JSlider sliderInteligencia;
    private javax.swing.JSlider sliderRecursosEco;
    private javax.swing.JSlider sliderVelocidad;
    private javax.swing.JSlider sliderVida;
    // End of variables declaration//GEN-END:variables

    private void actualizarPoderTotal() {
        int tSumaTotal = sliderFuerza.getValue() + sliderInteligencia.getValue() +
        sliderRecursosEco.getValue() + sliderVida.getValue() + sliderVelocidad.getValue();
        int tPoderTotal = (tSumaTotal * 100) / 500;
        labelPoderNum.setText("" + tPoderTotal);
    }
        
 
    private Personaje getInformacion() {
        String pseudonimo = inputPseudonimo.getText();
        TipoDeClase tipoDeClase = (TipoDeClase) inputTipoDeClase.getSelectedItem();  
        TipoDePersonaje tipoDePersonaje = (TipoDePersonaje) inputTipoDePersonaje.getSelectedItem();
        String franquicia = (String) inputFranquicia.getSelectedItem();
        int vida = sliderVida.getValue();
        int fuerza = sliderFuerza.getValue();
        int velocidad = sliderVelocidad.getValue();
        int inteligencia = sliderInteligencia.getValue();
        int recursosEco = sliderRecursosEco.getValue();
        Poder poder = new Poder(vida, fuerza, velocidad, inteligencia, recursosEco);
        DatosHeroe datosHeroe = new DatosHeroe(pseudonimo, tipoDeClase, tipoDePersonaje, poder);
        String nombreCompleto = inputNombre.getText();    
        Date date = inputFecha.getDate();  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        String strDate = dateFormat.format(date);
        DatosPersonales datosPersonales = new DatosPersonales(nombreCompleto, strDate, C_GestionHeroes.ciudad);
        Personaje personaje = new Personaje(datosHeroe, datosPersonales, franquicia, imagen);
        return personaje;
    }

    private void llenarInputs() {
        ArrayList lista = ManejoJSON.leerJSON(Personaje.RUTA, Personaje.class);
        Personaje personaje = (Personaje) lista.get(C_GestionHeroes.slotSeleccionadoNum);
        inputPseudonimo.setText(personaje.getpDatosHeroe().getmPseudonimo());
        inputTipoDeClase.setSelectedItem(personaje.getpDatosHeroe().getpTipoDeClase());
        inputTipoDePersonaje.setSelectedItem(personaje.getpDatosHeroe().getpTipoDePersonaje());
        inputFranquicia.setSelectedItem(personaje.getpFranquicia());
        sliderVida.setValue(personaje.getpDatosHeroe().getpPoder().getpVida());
        sliderFuerza.setValue(personaje.getpDatosHeroe().getpPoder().getpFuerza());
        sliderVelocidad.setValue(personaje.getpDatosHeroe().getpPoder().getpVelocidad());
        sliderInteligencia.setValue(personaje.getpDatosHeroe().getpPoder().getpInteligencia());
        sliderRecursosEco.setValue(personaje.getpDatosHeroe().getpPoder().getpRecursosEconomicos());
        actualizarPoderTotal();
        inputNombre.setText(personaje.getpDatosPersonales().getmNombreCompleto());
        
        Date fecha = null;  
        try {
            fecha = new SimpleDateFormat("yyyy-MM-dd").parse(personaje.getpDatosPersonales().getpFechaNacimiento());
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        inputFecha.setDate(fecha);
        inputCiudad.setText(C_GestionHeroes.ciudad.getCiudad());
        imagen = personaje.getpFotografia();    
        Image mImagen = new ImageIcon(imagen.getRuta()).getImage();
        ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(inputFoto.getWidth(), inputFoto.getHeight(), Image.SCALE_SMOOTH));
        inputFoto.setIcon(mIcono);
    }
}
