package gui;

import logicadenegocios.TipoDePersonaje;
import logicadenegocios.Poder;
import logicadenegocios.TipoDeClase;
import logicadenegocios.DatosPersonales;
import logicadenegocios.DatosHeroe;
import aplicacion.ManejoJSON;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import logicadenegocios.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Ginge
 */
public class C_GestionHeroesAux extends javax.swing.JFrame {
    public char modo;
    private Imagen imagen;
    /**
     * Creates new form ll_GestionHeroes
     * @param modo
     */
    public C_GestionHeroesAux(char modo) {
        this.modo = modo;
        initComponents();
        this.setLocationRelativeTo(null);
        
        inputTipoDeClase.setModel(new DefaultComboBoxModel<>(TipoDeClase.values()));
        inputTipoDePersonaje.setModel(new DefaultComboBoxModel<>(TipoDePersonaje.values()));  
        if (modo == 'a'){
            labelTitulo.setText("Nuevo Personaje");
        } else if (modo == 'm'){
            labelTitulo.setText("Modificar Personaje");
            llenarInputs();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistroUsuario = new javax.swing.JPanel();
        inputFoto = new javax.swing.JLabel();
        imagen = new Imagen("/recursos/defecto/foto.png");
        botonAgregarFoto = new javax.swing.JButton();
        inputNombre = new javax.swing.JTextField();
        inputFecha = new com.toedter.calendar.JDateChooser();
        labelFecha = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        inputCiudad = new javax.swing.JTextField();
        labelCiudad = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelFuerza = new javax.swing.JLabel();
        sliderFuerza = new javax.swing.JSlider();
        labelFuerzaNum = new javax.swing.JLabel();
        labelVida = new javax.swing.JLabel();
        sliderVida = new javax.swing.JSlider();
        labelVidaNum = new javax.swing.JLabel();
        labelVelocidadNum = new javax.swing.JLabel();
        labelVelocidad = new javax.swing.JLabel();
        labelInteligenciaNum = new javax.swing.JLabel();
        labelInteligencia = new javax.swing.JLabel();
        sliderInteligencia = new javax.swing.JSlider();
        sliderVelocidad = new javax.swing.JSlider();
        labelRecursosEco1 = new javax.swing.JLabel();
        sliderRecursosEco = new javax.swing.JSlider();
        labelRecursosEcoNum = new javax.swing.JLabel();
        labelPoderText = new javax.swing.JLabel();
        labelPoderNum = new javax.swing.JLabel();
        inputFranquicia = new javax.swing.JComboBox<>();
        labelFranquicia = new javax.swing.JLabel();
        inputTipoDePersonaje = new javax.swing.JComboBox<>();
        labelTipoDePersonaje = new javax.swing.JLabel();
        inputTipoDeClase = new javax.swing.JComboBox<>();
        labelTipoDeClase = new javax.swing.JLabel();
        inputPseudonimo = new javax.swing.JTextField();
        labelPseudonimo = new javax.swing.JLabel();
        botonCorrecto = new javax.swing.JButton();
        salir = new javax.swing.JLabel();
        atras = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRegistroUsuario.setBackground(new java.awt.Color(255, 255, 255, 220));
        panelRegistroUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panelRegistroUsuario.setForeground(new java.awt.Color(255, 255, 220, 220));
        panelRegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/defecto/foto.png"))); // NOI18N
        panelRegistroUsuario.add(inputFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        botonAgregarFoto.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        botonAgregarFoto.setText("Agregar Foto");
        botonAgregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarFotoActionPerformed(evt);
            }
        });
        panelRegistroUsuario.add(botonAgregarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, -1));
        panelRegistroUsuario.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 130, -1));
        panelRegistroUsuario.add(inputFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 130, -1));

        labelFecha.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFecha.setText("Fecha de nacimiento");
        panelRegistroUsuario.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 130, 30));

        labelNombre.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelNombre.setText("Nombre Completo");
        panelRegistroUsuario.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 120, 30));

        inputCiudad.setEditable(false);
        inputCiudad.setText(gui.C_GestionHeroes.ciudad.getCiudad());
        panelRegistroUsuario.add(inputCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 130, -1));

        labelCiudad.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelCiudad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCiudad.setText("Ciudad");
        panelRegistroUsuario.add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 100, 30));

        labelTitulo.setFont(new java.awt.Font("Comic Book", 0, 36)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Nuevo Personaje");
        panelRegistroUsuario.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 400, 30));

        labelFuerza.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelFuerza.setText("Fuerza");
        panelRegistroUsuario.add(labelFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        sliderFuerza.setMajorTickSpacing(25);
        sliderFuerza.setPaintTicks(true);
        sliderFuerza.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderFuerzaStateChanged(evt);
            }
        });
        panelRegistroUsuario.add(sliderFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        labelFuerzaNum.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelFuerzaNum.setText("50");
        panelRegistroUsuario.add(labelFuerzaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, 20));

        labelVida.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelVida.setText("Vida");
        panelRegistroUsuario.add(labelVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, 20));

        sliderVida.setMajorTickSpacing(25);
        sliderVida.setPaintTicks(true);
        sliderVida.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVidaStateChanged(evt);
            }
        });
        panelRegistroUsuario.add(sliderVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        labelVidaNum.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelVidaNum.setText("50");
        panelRegistroUsuario.add(labelVidaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, 20));

        labelVelocidadNum.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelVelocidadNum.setText("50");
        panelRegistroUsuario.add(labelVelocidadNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, 20));

        labelVelocidad.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelVelocidad.setText("Velocidad");
        panelRegistroUsuario.add(labelVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        labelInteligenciaNum.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelInteligenciaNum.setText("50");
        panelRegistroUsuario.add(labelInteligenciaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, 20));

        labelInteligencia.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelInteligencia.setText("Inteligencia");
        panelRegistroUsuario.add(labelInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        sliderInteligencia.setMajorTickSpacing(25);
        sliderInteligencia.setPaintTicks(true);
        sliderInteligencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderInteligenciaStateChanged(evt);
            }
        });
        panelRegistroUsuario.add(sliderInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        sliderVelocidad.setMajorTickSpacing(25);
        sliderVelocidad.setPaintTicks(true);
        sliderVelocidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVelocidadStateChanged(evt);
            }
        });
        panelRegistroUsuario.add(sliderVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        labelRecursosEco1.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelRecursosEco1.setText("Recursos Economicos");
        panelRegistroUsuario.add(labelRecursosEco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, 20));

        sliderRecursosEco.setMajorTickSpacing(25);
        sliderRecursosEco.setPaintTicks(true);
        sliderRecursosEco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderRecursosEcoStateChanged(evt);
            }
        });
        panelRegistroUsuario.add(sliderRecursosEco, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        labelRecursosEcoNum.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelRecursosEcoNum.setText("50");
        panelRegistroUsuario.add(labelRecursosEcoNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, 20));

        labelPoderText.setFont(new java.awt.Font("Comic Book", 0, 18)); // NOI18N
        labelPoderText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPoderText.setText("PODER");
        labelPoderText.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelRegistroUsuario.add(labelPoderText, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 90, 40));

        labelPoderNum.setFont(new java.awt.Font("Comic Book", 0, 18)); // NOI18N
        labelPoderNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPoderNum.setText("50");
        labelPoderNum.setToolTipText("");
        labelPoderNum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelRegistroUsuario.add(labelPoderNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 40, 40));

        inputFranquicia.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        inputFranquicia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marvel", "DC", "Otro" }));
        inputFranquicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFranquiciaActionPerformed(evt);
            }
        });
        panelRegistroUsuario.add(inputFranquicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 130, -1));

        labelFranquicia.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelFranquicia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFranquicia.setText("Franquicia");
        panelRegistroUsuario.add(labelFranquicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 80, 30));

        panelRegistroUsuario.add(inputTipoDePersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, -1));

        labelTipoDePersonaje.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelTipoDePersonaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTipoDePersonaje.setText("Tipo de Personaje");
        panelRegistroUsuario.add(labelTipoDePersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 30));

        inputTipoDeClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipoDeClaseActionPerformed(evt);
            }
        });
        panelRegistroUsuario.add(inputTipoDeClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, -1));

        labelTipoDeClase.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelTipoDeClase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTipoDeClase.setText("Tipo de Clase");
        panelRegistroUsuario.add(labelTipoDeClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 90, 30));
        panelRegistroUsuario.add(inputPseudonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 131, -1));

        labelPseudonimo.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        labelPseudonimo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPseudonimo.setText("Pseudonimo");
        panelRegistroUsuario.add(labelPseudonimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 90, 30));

        botonCorrecto.setFont(new java.awt.Font("Comic Book", 0, 12)); // NOI18N
        botonCorrecto.setText("Confirmar");
        botonCorrecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCorrectoActionPerformed(evt);
            }
        });
        panelRegistroUsuario.add(botonCorrecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 120, -1));

        getContentPane().add(panelRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 760, 430));

        salir.setFont(new java.awt.Font("Comic Book", 0, 18)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 0, 70, 40));

        atras.setFont(new java.awt.Font("Comic Book", 0, 18)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atras.setText("Atrás");
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atrasMouseClicked(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 60, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/gestionHeroes.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFranquiciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFranquiciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFranquiciaActionPerformed

    private void botonCorrectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCorrectoActionPerformed
        if(inputNombre.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Rellene el nombre completo", "Error", JOptionPane.WARNING_MESSAGE);      
        }else if (inputFecha.getDate() == null){
            JOptionPane.showMessageDialog(null, "Rellene la fecha de nacimiento", "Error", JOptionPane.WARNING_MESSAGE);
        }else if (inputPseudonimo.getText().trim().isEmpty()){
   
        }else{
            Personaje personaje = getInformacion();  
            if (modo == 'a'){
                ManejoJSON.guardarJSON(personaje, Personaje.RUTA);
            } else if (modo == 'm'){
                ManejoJSON.modificarJSON(personaje, C_GestionHeroes.slotSeleccionadoNum, Personaje.RUTA);
            }
            C_GestionHeroes gestionHeroes = new C_GestionHeroes();
            gestionHeroes.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_botonCorrectoActionPerformed

    private void botonAgregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarFotoActionPerformed
        String Ruta = "";
        JFileChooser jFileChooser = new JFileChooser("C:\\Users\\emifu\\Desktop\\ProyectoII_Marvel_v3\\src\\recursos");
        FileNameExtensionFilter filtrado = new FileNameExtensionFilter("JGP, PNG & GIF", "jpg", "png", "gif");
        jFileChooser.setFileFilter(filtrado);
        
        
        int respuesta = jFileChooser.showOpenDialog(this);
        
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            Ruta = jFileChooser.getSelectedFile().getPath();
            imagen = new Imagen(Ruta);
            Image mImagen = new ImageIcon(Ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(inputFoto.getWidth(), inputFoto.getHeight(), Image.SCALE_SMOOTH));
            inputFoto.setIcon(mIcono); 
            
        }
    }//GEN-LAST:event_botonAgregarFotoActionPerformed

    private void inputTipoDeClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipoDeClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipoDeClaseActionPerformed

    private void sliderFuerzaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderFuerzaStateChanged
        labelFuerzaNum.setText( "" + sliderFuerza.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderFuerzaStateChanged

    private void sliderRecursosEcoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRecursosEcoStateChanged
        labelRecursosEcoNum.setText( "" + sliderRecursosEco.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderRecursosEcoStateChanged

    private void sliderVidaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVidaStateChanged
        labelVidaNum.setText( "" + sliderVida.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderVidaStateChanged

    private void sliderInteligenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderInteligenciaStateChanged
        labelInteligenciaNum.setText( "" + sliderInteligencia.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderInteligenciaStateChanged

    private void sliderVelocidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVelocidadStateChanged
        labelVelocidadNum.setText( "" + sliderVelocidad.getValue() );
        actualizarPoderTotal();
    }//GEN-LAST:event_sliderVelocidadStateChanged

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseClicked
        C_GestionHeroes nf = new C_GestionHeroes();
        nf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_GestionHeroesAux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private char modo;
            @Override
            public void run() {
                new C_GestionHeroesAux(modo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atras;
    private javax.swing.JButton botonAgregarFoto;
    private javax.swing.JButton botonCorrecto;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField inputCiudad;
    private com.toedter.calendar.JDateChooser inputFecha;
    public static javax.swing.JLabel inputFoto;
    private javax.swing.JComboBox<String> inputFranquicia;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputPseudonimo;
    private javax.swing.JComboBox<TipoDeClase> inputTipoDeClase;
    private javax.swing.JComboBox<TipoDePersonaje> inputTipoDePersonaje;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFranquicia;
    private javax.swing.JLabel labelFuerza;
    private javax.swing.JLabel labelFuerzaNum;
    private javax.swing.JLabel labelInteligencia;
    private javax.swing.JLabel labelInteligenciaNum;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPoderNum;
    private javax.swing.JLabel labelPoderText;
    private javax.swing.JLabel labelPseudonimo;
    private javax.swing.JLabel labelRecursosEco1;
    private javax.swing.JLabel labelRecursosEcoNum;
    private javax.swing.JLabel labelTipoDeClase;
    private javax.swing.JLabel labelTipoDePersonaje;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelVelocidad;
    private javax.swing.JLabel labelVelocidadNum;
    private javax.swing.JLabel labelVida;
    private javax.swing.JLabel labelVidaNum;
    private javax.swing.JPanel panelRegistroUsuario;
    private javax.swing.JLabel salir;
    private javax.swing.JSlider sliderFuerza;
    private javax.swing.JSlider sliderInteligencia;
    private javax.swing.JSlider sliderRecursosEco;
    private javax.swing.JSlider sliderVelocidad;
    private javax.swing.JSlider sliderVida;
    // End of variables declaration//GEN-END:variables

    private void actualizarPoderTotal() {
        int tSumaTotal = sliderFuerza.getValue() + sliderInteligencia.getValue() +
        sliderRecursosEco.getValue() + sliderVida.getValue() + sliderVelocidad.getValue();
        int tPoderTotal = (tSumaTotal * 100) / 500;
        labelPoderNum.setText("" + tPoderTotal);
    }
        
 
    private Personaje getInformacion() {
        String pseudonimo = inputPseudonimo.getText();
        TipoDeClase tipoDeClase = (TipoDeClase) inputTipoDeClase.getSelectedItem();  
        TipoDePersonaje tipoDePersonaje = (TipoDePersonaje) inputTipoDePersonaje.getSelectedItem();
        String franquicia = (String) inputFranquicia.getSelectedItem();
        int vida = sliderVida.getValue();
        int fuerza = sliderFuerza.getValue();
        int velocidad = sliderVelocidad.getValue();
        int inteligencia = sliderInteligencia.getValue();
        int recursosEco = sliderRecursosEco.getValue();
        Poder poder = new Poder(vida, fuerza, velocidad, inteligencia, recursosEco);
        DatosHeroe datosHeroe = new DatosHeroe(pseudonimo, tipoDeClase, tipoDePersonaje, poder);
        String nombreCompleto = inputNombre.getText();    
        Date date = inputFecha.getDate();  
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
        String strDate = dateFormat.format(date);
        DatosPersonales datosPersonales = new DatosPersonales(nombreCompleto, strDate, C_GestionHeroes.ciudad);
        Personaje personaje = new Personaje(datosHeroe, datosPersonales, franquicia, imagen);
        return personaje;
    }

    private void llenarInputs() {
        ArrayList lista = ManejoJSON.leerJSON(Personaje.RUTA, Personaje.class);
        Personaje personaje = (Personaje) lista.get(C_GestionHeroes.slotSeleccionadoNum);
        inputPseudonimo.setText(personaje.getpDatosHeroe().getmPseudonimo());
        inputTipoDeClase.setSelectedItem(personaje.getpDatosHeroe().getpTipoDeClase());
        inputTipoDePersonaje.setSelectedItem(personaje.getpDatosHeroe().getpTipoDePersonaje());
        inputFranquicia.setSelectedItem(personaje.getpFranquicia());
        sliderVida.setValue(personaje.getpDatosHeroe().getpPoder().getpVida());
        sliderFuerza.setValue(personaje.getpDatosHeroe().getpPoder().getpFuerza());
        sliderVelocidad.setValue(personaje.getpDatosHeroe().getpPoder().getpVelocidad());
        sliderInteligencia.setValue(personaje.getpDatosHeroe().getpPoder().getpInteligencia());
        sliderRecursosEco.setValue(personaje.getpDatosHeroe().getpPoder().getpRecursosEconomicos());
        actualizarPoderTotal();
        inputNombre.setText(personaje.getpDatosPersonales().getmNombreCompleto());
        
        Date fecha = null;  
        try {
            fecha = new SimpleDateFormat("yyyy-MM-dd").parse(personaje.getpDatosPersonales().getpFechaNacimiento());
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        inputFecha.setDate(fecha);
        inputCiudad.setText(C_GestionHeroes.ciudad.getCiudad());
        imagen = personaje.getpFotografia();    
        Image mImagen = new ImageIcon(imagen.getRuta()).getImage();
        ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(inputFoto.getWidth(), inputFoto.getHeight(), Image.SCALE_SMOOTH));
        inputFoto.setIcon(mIcono);
    }
}
