package gui;

import aplicacion.ManejoJSON;
import aplicacion.ManejoJSON;
import gui.B_Servidores;
import gui.D_JuegoCliente;
import gui.D_JuegoServidor;
import static aplicacion.ManejoJSON.borrarTodoJSON;
import static gui.C_GestionHeroes.ciudad;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import logicadenegocios.*;
import static logicadenegocios.TipoDeClase.COSMICO;
import static logicadenegocios.TipoDeClase.HABIL;
import static logicadenegocios.TipoDeClase.MISTICO;
import static logicadenegocios.TipoDeClase.MUTANTE;
import static logicadenegocios.TipoDeClase.TECNOLOGICO;
import static logicadenegocios.TipoDePersonaje.ANTIHEROE;
import static logicadenegocios.TipoDePersonaje.HEROE;
import static logicadenegocios.TipoDePersonaje.VILLANO;
/**
 *
 * @author emifu
 */
public class SeleccionarHeroe extends javax.swing.JFrame {
    
    private String tipo;
    private javax.swing.JPanel slotSeleccionado = null;
    public static int slotSeleccionadoNum = -1;
    private ArrayList<Personaje> personajes;
    public static Ciudad ciudad;
    private ServidorLocal servidorLocal;
    
    private ArrayList<javax.swing.JPanel> slotsOcupados;
    private ArrayList<javax.swing.JLabel> slotsVacios;
    private ArrayList<javax.swing.JLabel> nombres;
    private ArrayList<javax.swing.JLabel> tipos;
    private ArrayList<javax.swing.JLabel> clases;
    private ArrayList<javax.swing.JLabel> stats;
    private ArrayList<javax.swing.JLabel> poderes;
    private ArrayList<javax.swing.JLabel> imagenes;
    
    /**
     * Creates new form I_MenuInicio
     * @param tipo
     * @param servidorLocal
     */
    public SeleccionarHeroe(String tipo, ServidorLocal servidorLocal) {
        this.tipo = tipo;
        this.servidorLocal = servidorLocal;
        this.personajes = new ArrayList<>();
        this.slotsOcupados = new ArrayList<>();
        this.slotsVacios = new ArrayList<>();
        this.nombres = new ArrayList<>();
        this.tipos = new ArrayList<>();
        this.clases = new ArrayList<>();
        this.stats = new ArrayList<>();
        this.poderes = new ArrayList<>();
        this.imagenes = new ArrayList<>();        
        initComponents();
        this.setLocationRelativeTo(null);
        
        llenarListaObjetos();
        vaciarSlots();
        actualizarSlots();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new java.awt.Panel();
        slotPersonaje1 = new javax.swing.JPanel();
        slotVacio1 = new javax.swing.JLabel();
        slotOcupado1 = new javax.swing.JPanel();
        slotNombre1 = new javax.swing.JLabel();
        slotTipo1 = new javax.swing.JLabel();
        slotClase1 = new javax.swing.JLabel();
        slotStats1 = new javax.swing.JLabel();
        slotPoder1 = new javax.swing.JLabel();
        slotImagen1 = new javax.swing.JLabel();
        slotPersonaje2 = new javax.swing.JPanel();
        slotVacio2 = new javax.swing.JLabel();
        slotOcupado2 = new javax.swing.JPanel();
        slotNombre2 = new javax.swing.JLabel();
        slotTipo2 = new javax.swing.JLabel();
        slotClase2 = new javax.swing.JLabel();
        slotStats2 = new javax.swing.JLabel();
        slotPoder2 = new javax.swing.JLabel();
        slotImagen2 = new javax.swing.JLabel();
        slotPersonaje3 = new javax.swing.JPanel();
        slotVacio3 = new javax.swing.JLabel();
        slotOcupado3 = new javax.swing.JPanel();
        slotNombre3 = new javax.swing.JLabel();
        slotTipo3 = new javax.swing.JLabel();
        slotClase3 = new javax.swing.JLabel();
        slotStats3 = new javax.swing.JLabel();
        slotPoder3 = new javax.swing.JLabel();
        slotImagen3 = new javax.swing.JLabel();
        slotPersonaje4 = new javax.swing.JPanel();
        slotVacio4 = new javax.swing.JLabel();
        slotOcupado4 = new javax.swing.JPanel();
        slotNombre4 = new javax.swing.JLabel();
        slotTipo4 = new javax.swing.JLabel();
        slotClase4 = new javax.swing.JLabel();
        slotStats4 = new javax.swing.JLabel();
        slotPoder4 = new javax.swing.JLabel();
        slotImagen4 = new javax.swing.JLabel();
        slotPersonaje5 = new javax.swing.JPanel();
        slotVacio5 = new javax.swing.JLabel();
        slotOcupado5 = new javax.swing.JPanel();
        slotNombre5 = new javax.swing.JLabel();
        slotTipo5 = new javax.swing.JLabel();
        slotClase5 = new javax.swing.JLabel();
        slotStats5 = new javax.swing.JLabel();
        slotPoder5 = new javax.swing.JLabel();
        slotImagen5 = new javax.swing.JLabel();
        slotPersonaje6 = new javax.swing.JPanel();
        slotVacio6 = new javax.swing.JLabel();
        slotOcupado6 = new javax.swing.JPanel();
        slotNombre6 = new javax.swing.JLabel();
        slotTipo6 = new javax.swing.JLabel();
        slotClase6 = new javax.swing.JLabel();
        slotStats6 = new javax.swing.JLabel();
        slotPoder6 = new javax.swing.JLabel();
        slotImagen6 = new javax.swing.JLabel();
        slotPersonaje7 = new javax.swing.JPanel();
        slotVacio7 = new javax.swing.JLabel();
        slotOcupado7 = new javax.swing.JPanel();
        slotNombre7 = new javax.swing.JLabel();
        slotTipo7 = new javax.swing.JLabel();
        slotClase7 = new javax.swing.JLabel();
        slotStats7 = new javax.swing.JLabel();
        slotPoder7 = new javax.swing.JLabel();
        slotImagen7 = new javax.swing.JLabel();
        slotPersonaje8 = new javax.swing.JPanel();
        slotVacio8 = new javax.swing.JLabel();
        slotOcupado8 = new javax.swing.JPanel();
        slotNombre8 = new javax.swing.JLabel();
        slotTipo8 = new javax.swing.JLabel();
        slotClase8 = new javax.swing.JLabel();
        slotStats8 = new javax.swing.JLabel();
        slotPoder8 = new javax.swing.JLabel();
        slotImagen8 = new javax.swing.JLabel();
        slotPersonaje9 = new javax.swing.JPanel();
        slotVacio9 = new javax.swing.JLabel();
        slotOcupado9 = new javax.swing.JPanel();
        slotNombre9 = new javax.swing.JLabel();
        slotTipo9 = new javax.swing.JLabel();
        slotClase9 = new javax.swing.JLabel();
        slotStats9 = new javax.swing.JLabel();
        slotPoder9 = new javax.swing.JLabel();
        slotImagen9 = new javax.swing.JLabel();
        slotPersonaje10 = new javax.swing.JPanel();
        slotVacio10 = new javax.swing.JLabel();

        slotOcupado10 = new javax.swing.JPanel();
        slotNombre10 = new javax.swing.JLabel();
        slotTipo10 = new javax.swing.JLabel();
        slotClase10 = new javax.swing.JLabel();
        slotStats10 = new javax.swing.JLabel();
        slotPoder10 = new javax.swing.JLabel();
        slotImagen10 = new javax.swing.JLabel();
        botonSeleccionar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(900, 500));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotPersonaje1.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje1.setOpaque(false);
        slotPersonaje1.setPreferredSize(new java.awt.Dimension(440, 90));
        slotPersonaje1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot1(evt);
            }
        });
        slotPersonaje1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio1.setText("<Vacio>");
        slotPersonaje1.add(slotVacio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado1.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre1.setText("Nombre");
        slotOcupado1.add(slotNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado1.add(slotTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado1.add(slotClase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado1.add(slotStats1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder1.setText("00");
        slotPoder1.setToolTipText("");
        slotOcupado1.add(slotPoder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado1.add(slotImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje1.add(slotOcupado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        slotPersonaje2.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje2.setOpaque(false);
        slotPersonaje2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot2(evt);
            }
        });
        slotPersonaje2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio2.setText("<Vacio>");
        slotPersonaje2.add(slotVacio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado2.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre2.setText("Nombre");
        slotOcupado2.add(slotNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado2.add(slotTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado2.add(slotClase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado2.add(slotStats2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder2.setText("00");
        slotPoder2.setToolTipText("");
        slotOcupado2.add(slotPoder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado2.add(slotImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje2.add(slotOcupado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        slotPersonaje3.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje3.setOpaque(false);
        slotPersonaje3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot3(evt);
            }
        });
        slotPersonaje3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio3.setText("<Vacio>");
        slotPersonaje3.add(slotVacio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado3.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre3.setText("Nombre");
        slotOcupado3.add(slotNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado3.add(slotTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado3.add(slotClase3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado3.add(slotStats3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder3.setText("00");
        slotPoder3.setToolTipText("");
        slotOcupado3.add(slotPoder3, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado3.add(slotImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje3.add(slotOcupado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        slotPersonaje4.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje4.setOpaque(false);
        slotPersonaje4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot4(evt);
            }
        });
        slotPersonaje4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio4.setText("<Vacio>");
        slotPersonaje4.add(slotVacio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado4.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre4.setText("Nombre");
        slotOcupado4.add(slotNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado4.add(slotTipo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado4.add(slotClase4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado4.add(slotStats4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder4.setText("00");
        slotPoder4.setToolTipText("");
        slotOcupado4.add(slotPoder4, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado4.add(slotImagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje4.add(slotOcupado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        slotPersonaje5.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje5.setOpaque(false);
        slotPersonaje5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot5(evt);
            }
        });
        slotPersonaje5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio5.setText("<Vacio>");
        slotPersonaje5.add(slotVacio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado5.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre5.setText("Nombre");
        slotOcupado5.add(slotNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado5.add(slotTipo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado5.add(slotClase5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado5.add(slotStats5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder5.setText("00");
        slotPoder5.setToolTipText("");
        slotOcupado5.add(slotPoder5, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado5.add(slotImagen5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje5.add(slotOcupado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        slotPersonaje6.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje6.setOpaque(false);
        slotPersonaje6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot6(evt);
            }
        });
        slotPersonaje6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio6.setText("<Vacio>");
        slotPersonaje6.add(slotVacio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado6.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre6.setText("Nombre");
        slotOcupado6.add(slotNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado6.add(slotTipo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado6.add(slotClase6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado6.add(slotStats6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder6.setText("00");
        slotPoder6.setToolTipText("");
        slotOcupado6.add(slotPoder6, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado6.add(slotImagen6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje6.add(slotOcupado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        slotPersonaje7.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje7.setOpaque(false);
        slotPersonaje7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot7(evt);
            }
        });
        slotPersonaje7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio7.setText("<Vacio>");
        slotPersonaje7.add(slotVacio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado7.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre7.setText("Nombre");
        slotOcupado7.add(slotNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado7.add(slotTipo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado7.add(slotClase7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado7.add(slotStats7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder7.setText("00");
        slotPoder7.setToolTipText("");
        slotOcupado7.add(slotPoder7, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado7.add(slotImagen7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje7.add(slotOcupado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        slotPersonaje8.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje8.setOpaque(false);
        slotPersonaje8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot8(evt);
            }
        });
        slotPersonaje8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio8.setText("<Vacio>");
        slotPersonaje8.add(slotVacio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado8.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre8.setText("Nombre");
        slotOcupado8.add(slotNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado8.add(slotTipo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado8.add(slotClase8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado8.add(slotStats8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder8.setText("00");
        slotPoder8.setToolTipText("");
        slotOcupado8.add(slotPoder8, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado8.add(slotImagen8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje8.add(slotOcupado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        slotPersonaje9.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje9.setOpaque(false);
        slotPersonaje9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot9(evt);
            }
        });
        slotPersonaje9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio9.setText("<Vacio>");
        slotPersonaje9.add(slotVacio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado9.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre9.setText("Nombre");
        slotOcupado9.add(slotNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado9.add(slotTipo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado9.add(slotClase9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado9.add(slotStats9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder9.setText("00");
        slotPoder9.setToolTipText("");
        slotOcupado9.add(slotPoder9, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado9.add(slotImagen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje9.add(slotOcupado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        slotPersonaje10.setBackground(new java.awt.Color(204, 204, 255));
        slotPersonaje10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        slotPersonaje10.setOpaque(false);
        slotPersonaje10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSlot10(evt);
            }
        });
        slotPersonaje10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotVacio10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotVacio10.setText("<Vacio>");
        slotPersonaje10.add(slotVacio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 90));

        slotOcupado10.setBackground(new java.awt.Color(255, 255, 255));
        slotOcupado10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slotNombre10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        slotNombre10.setText("Nombre");
        slotOcupado10.add(slotNombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 130, 30));
        slotOcupado10.add(slotTipo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, 20));
        slotOcupado10.add(slotClase10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 20, 20));

        slotStats10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        slotOcupado10.add(slotStats10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 36, 140, 30));

        slotPoder10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        slotPoder10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slotPoder10.setText("00");
        slotPoder10.setToolTipText("");
        slotOcupado10.add(slotPoder10, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 30, 40, 40));
        slotOcupado10.add(slotImagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 70));

        slotPersonaje10.add(slotOcupado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 70));

        fondo.add(slotPersonaje10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        botonSeleccionar.setText("Seleccionar");
        botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarActionPerformed(evt);
            }
        });
        fondo.add(botonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 110, -1));

        botonGuardar.setText("Regresar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        fondo.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bg/gestionHeroes.png"))); // NOI18N
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        if ( tipo.equals("Servidor")){  
            D_JuegoServidor ph = new D_JuegoServidor(servidorLocal);
            ph.setVisible(true);          
        } else {
            D_JuegoCliente jc = new D_JuegoCliente( B_Servidores.puertoSeleccionado);
            jc.setVisible(true);
            
        }     
        this.dispose();
        
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void clickSlot1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot1
        slotPersonaje1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje1;
        slotSeleccionadoNum = 0;
    }//GEN-LAST:event_clickSlot1

    private void clickSlot2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot2
        slotPersonaje2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje2;
        slotSeleccionadoNum = 1;
    }//GEN-LAST:event_clickSlot2

    private void clickSlot3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot3
        slotPersonaje3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje3;
        slotSeleccionadoNum = 2;
    }//GEN-LAST:event_clickSlot3

    private void clickSlot4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot4
        slotPersonaje4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje4;
        slotSeleccionadoNum = 3;
    }//GEN-LAST:event_clickSlot4

    private void clickSlot5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot5
        slotPersonaje5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje5;
        slotSeleccionadoNum = 4;
    }//GEN-LAST:event_clickSlot5

    private void clickSlot6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot6
        slotPersonaje6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje6;
        slotSeleccionadoNum = 5;
    }//GEN-LAST:event_clickSlot6

    private void clickSlot7(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot7
        slotPersonaje7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje7;
        slotSeleccionadoNum = 6;
    }//GEN-LAST:event_clickSlot7

    private void clickSlot8(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot8
        slotPersonaje8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje8;
        slotSeleccionadoNum = 7;
    }//GEN-LAST:event_clickSlot8

    private void clickSlot9(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot9
        slotPersonaje9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje9;
        slotSeleccionadoNum = 8;
    }//GEN-LAST:event_clickSlot9

    private void clickSlot10(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSlot10
        slotPersonaje10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        if (slotSeleccionado != null){
            slotSeleccionado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));            
        }
        slotSeleccionado = slotPersonaje10;
        slotSeleccionadoNum = 9;
    }//GEN-LAST:event_clickSlot10

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarHeroe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SeleccionarHeroe(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSeleccionar;
    private java.awt.Panel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel slotClase1;
    private javax.swing.JLabel slotClase10;
    private javax.swing.JLabel slotClase2;
    private javax.swing.JLabel slotClase3;
    private javax.swing.JLabel slotClase4;
    private javax.swing.JLabel slotClase5;
    private javax.swing.JLabel slotClase6;
    private javax.swing.JLabel slotClase7;
    private javax.swing.JLabel slotClase8;
    private javax.swing.JLabel slotClase9;
    private javax.swing.JLabel slotImagen1;
    private javax.swing.JLabel slotImagen10;
    private javax.swing.JLabel slotImagen2;
    private javax.swing.JLabel slotImagen3;
    private javax.swing.JLabel slotImagen4;
    private javax.swing.JLabel slotImagen5;
    private javax.swing.JLabel slotImagen6;
    private javax.swing.JLabel slotImagen7;
    private javax.swing.JLabel slotImagen8;
    private javax.swing.JLabel slotImagen9;
    private javax.swing.JLabel slotNombre1;
    private javax.swing.JLabel slotNombre10;
    private javax.swing.JLabel slotNombre2;
    private javax.swing.JLabel slotNombre3;
    private javax.swing.JLabel slotNombre4;
    private javax.swing.JLabel slotNombre5;
    private javax.swing.JLabel slotNombre6;
    private javax.swing.JLabel slotNombre7;
    private javax.swing.JLabel slotNombre8;
    private javax.swing.JLabel slotNombre9;
    private javax.swing.JPanel slotOcupado1;
    private javax.swing.JPanel slotOcupado10;
    private javax.swing.JPanel slotOcupado2;
    private javax.swing.JPanel slotOcupado3;
    private javax.swing.JPanel slotOcupado4;
    private javax.swing.JPanel slotOcupado5;
    private javax.swing.JPanel slotOcupado6;
    private javax.swing.JPanel slotOcupado7;
    private javax.swing.JPanel slotOcupado8;
    private javax.swing.JPanel slotOcupado9;
    private javax.swing.JPanel slotPersonaje1;
    private javax.swing.JPanel slotPersonaje10;
    private javax.swing.JPanel slotPersonaje2;
    private javax.swing.JPanel slotPersonaje3;
    private javax.swing.JPanel slotPersonaje4;
    private javax.swing.JPanel slotPersonaje5;
    private javax.swing.JPanel slotPersonaje6;
    private javax.swing.JPanel slotPersonaje7;
    private javax.swing.JPanel slotPersonaje8;
    private javax.swing.JPanel slotPersonaje9;
    private javax.swing.JLabel slotPoder1;
    private javax.swing.JLabel slotPoder10;
    private javax.swing.JLabel slotPoder2;
    private javax.swing.JLabel slotPoder3;
    private javax.swing.JLabel slotPoder4;
    private javax.swing.JLabel slotPoder5;
    private javax.swing.JLabel slotPoder6;
    private javax.swing.JLabel slotPoder7;
    private javax.swing.JLabel slotPoder8;
    private javax.swing.JLabel slotPoder9;
    private javax.swing.JLabel slotStats1;
    private javax.swing.JLabel slotStats10;
    private javax.swing.JLabel slotStats2;
    private javax.swing.JLabel slotStats3;
    private javax.swing.JLabel slotStats4;
    private javax.swing.JLabel slotStats5;
    private javax.swing.JLabel slotStats6;
    private javax.swing.JLabel slotStats7;
    private javax.swing.JLabel slotStats8;
    private javax.swing.JLabel slotStats9;
    private javax.swing.JLabel slotTipo1;
    private javax.swing.JLabel slotTipo10;
    private javax.swing.JLabel slotTipo2;
    private javax.swing.JLabel slotTipo3;
    private javax.swing.JLabel slotTipo4;
    private javax.swing.JLabel slotTipo5;
    private javax.swing.JLabel slotTipo6;
    private javax.swing.JLabel slotTipo7;
    private javax.swing.JLabel slotTipo8;
    private javax.swing.JLabel slotTipo9;
    private javax.swing.JLabel slotVacio1;
    private javax.swing.JLabel slotVacio10;
    private javax.swing.JLabel slotVacio2;
    private javax.swing.JLabel slotVacio3;
    private javax.swing.JLabel slotVacio4;
    private javax.swing.JLabel slotVacio5;
    private javax.swing.JLabel slotVacio6;
    private javax.swing.JLabel slotVacio7;
    private javax.swing.JLabel slotVacio8;
    private javax.swing.JLabel slotVacio9;
    // End of variables declaration//GEN-END:variables

    private void actualizarSlots() {
        ArrayList<Personaje> filtro = new ArrayList();
        filtro = ManejoJSON.leerJSON(Personaje.RUTA, Personaje.class);
        for (int i = 0; i < filtro.size(); i++){
            if ( filtro.get(i).getpDatosPersonales().getpCiudad().getCiudad().equals(ciudad.getCiudad()) ){
                personajes.add(filtro.get(i));            
            } 
        }
        ImageIcon mIcono = null;
        for (int i = 0; i < personajes.size(); i++){
            
            slotsOcupados.get(i).setVisible(true);
            slotsOcupados.get(i).setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));  
            slotsVacios.get(i).setVisible(false);

            //Nombre
            nombres.get(i).setText(personajes.get(i).getpDatosHeroe().getmPseudonimo());
            //Icono Clase
            switch (personajes.get(i).getpDatosHeroe().getpTipoDeClase()) {
                case HABIL -> clases.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/claseHabil.png")));
                case TECNOLOGICO -> clases.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/claseTecnologico.png")));
                case COSMICO -> clases.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/claseCosmico.png")));
                case MISTICO -> clases.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/claseMistico.png")));
                case MUTANTE -> clases.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/claseMutante.png")));
                default -> {
                }
            }
            //Icono Tipo Personaje
            switch (personajes.get(i).getpDatosHeroe().getpTipoDePersonaje()) {
                case ANTIHEROE -> tipos.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/antiheroe.png")));
                case HEROE -> tipos.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/heroe.png")));
                case VILLANO -> tipos.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconos/villano.png")));
                default -> {
                }
            }

            //Estadisticas
            Poder tPoder = personajes.get(i).getpDatosHeroe().getpPoder();
            String tStats = "HP: " + tPoder.getpVida() + " F: " + tPoder.getpFuerza()
                    + " V: " + tPoder.getpVelocidad() + " I: " + tPoder.getpInteligencia()
                    + " RE: " + tPoder.getpRecursosEconomicos();
            stats.get(i).setText(tStats);

            //Poder Total
            int tPoderTotal = personajes.get(i).getpDatosHeroe().getpPoder().poderTotal();
            poderes.get(i).setText("" + tPoderTotal);

            // Imagen Fondo

            switch (personajes.get(i).getpDatosHeroe().getmPseudonimo()) {
                case "BrujaEscarlata" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/BrujaEscarlata/lowerThird.png")));
                case "Carnage" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Carnage/lowerThird.png")));
                case "Daredevil" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Daredevil/lowerThird.png")));
                case "Deadpool" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Deadpool/lowerThird.png")));
                case "Morgan" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Morgan/lowerThird.png")));
                case "Quicksilver" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Quicksilver/lowerThird.png")));
                case "Rocket" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Rocket/lowerThird.png")));
                case "Ultron" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Ultron/lowerThird.png")));
                case "Venom" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Venom/lowerThird.png")));
                case "Viper" -> imagenes.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Viper/lowerThird.png")));
                default -> {
                }
            }
        }
    }
    
    private void vaciarSlots() {
        slotOcupado1.setVisible(false);
        slotOcupado2.setVisible(false);
        slotOcupado3.setVisible(false);
        slotOcupado4.setVisible(false);
        slotOcupado5.setVisible(false);
        slotOcupado6.setVisible(false);
        slotOcupado7.setVisible(false);
        slotOcupado8.setVisible(false);
        slotOcupado9.setVisible(false);
        slotOcupado10.setVisible(false);
        slotVacio1.setVisible(true);
        slotVacio2.setVisible(true);
        slotVacio3.setVisible(true);
        slotVacio4.setVisible(true);
        slotVacio5.setVisible(true);
        slotVacio6.setVisible(true);
        slotVacio7.setVisible(true);
        slotVacio8.setVisible(true);
        slotVacio9.setVisible(true);
        slotVacio10.setVisible(true);
        
    }

    private void llenarListaObjetos() {
        slotsOcupados.add(slotOcupado1);
        slotsOcupados.add(slotOcupado2);
        slotsOcupados.add(slotOcupado3);
        slotsOcupados.add(slotOcupado4);
        slotsOcupados.add(slotOcupado5);
        slotsOcupados.add(slotOcupado6);
        slotsOcupados.add(slotOcupado7);
        slotsOcupados.add(slotOcupado8);
        slotsOcupados.add(slotOcupado9);
        slotsOcupados.add(slotOcupado10);
        
        slotsVacios.add(slotVacio1);
        slotsVacios.add(slotVacio2);
        slotsVacios.add(slotVacio3);
        slotsVacios.add(slotVacio4);
        slotsVacios.add(slotVacio5);
        slotsVacios.add(slotVacio6);
        slotsVacios.add(slotVacio7);
        slotsVacios.add(slotVacio8);
        slotsVacios.add(slotVacio9);
        slotsVacios.add(slotVacio10);
        
        nombres.add(slotNombre1);
        nombres.add(slotNombre2);
        nombres.add(slotNombre3);
        nombres.add(slotNombre4);
        nombres.add(slotNombre5);
        nombres.add(slotNombre6);
        nombres.add(slotNombre7);
        nombres.add(slotNombre8);
        nombres.add(slotNombre9);
        nombres.add(slotNombre10);
       
        tipos.add(slotTipo1);
        tipos.add(slotTipo2);
        tipos.add(slotTipo3);
        tipos.add(slotTipo4);
        tipos.add(slotTipo5);
        tipos.add(slotTipo6);
        tipos.add(slotTipo7);
        tipos.add(slotTipo8);
        tipos.add(slotTipo9);
        tipos.add(slotTipo10);
        
        clases.add(slotClase1);
        clases.add(slotClase2);
        clases.add(slotClase3);
        clases.add(slotClase4);
        clases.add(slotClase5);
        clases.add(slotClase6);
        clases.add(slotClase7);
        clases.add(slotClase8);
        clases.add(slotClase9);
        clases.add(slotClase10);
        
        stats.add(slotStats1);
        stats.add(slotStats2);
        stats.add(slotStats3);
        stats.add(slotStats4);
        stats.add(slotStats5);
        stats.add(slotStats6);
        stats.add(slotStats7);
        stats.add(slotStats8);
        stats.add(slotStats9);
        stats.add(slotStats10);
        
        poderes.add(slotPoder1);
        poderes.add(slotPoder2);
        poderes.add(slotPoder3);
        poderes.add(slotPoder4);
        poderes.add(slotPoder5);
        poderes.add(slotPoder6);
        poderes.add(slotPoder7);
        poderes.add(slotPoder8);
        poderes.add(slotPoder9);
        poderes.add(slotPoder10);
        
        imagenes.add(slotImagen1);
        imagenes.add(slotImagen2);
        imagenes.add(slotImagen3);
        imagenes.add(slotImagen4);
        imagenes.add(slotImagen5);
        imagenes.add(slotImagen6);
        imagenes.add(slotImagen7);
        imagenes.add(slotImagen8);
        imagenes.add(slotImagen9);
        imagenes.add(slotImagen10);
    }
}
