/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author emifu
 */
public class SpritePersonaje extends javax.swing.JPanel {
    private final Image BRUJAESCARLATA_ATAQUE1 = new ImageIcon("src/recursos/BrujaEscarlata/ataque1.png").getImage();
    private final Image CARNAGE_ATAQUE1 = new ImageIcon("src/recursos/Carnage/ataque1.png").getImage();
    private final Image DAREDEVIL_ATAQUE1 = new ImageIcon("src/recursos/Daredevil/ataque1.png").getImage();
    private final Image DEADPOOL_ATAQUE1 = new ImageIcon("src/recursos/Deadpool/ataque1.png").getImage();
    private final Image MORGAN_ATAQUE1 = new ImageIcon("src/recursos/Morgan/ataque1.png").getImage();
    private final Image QUICKSILVER_ATAQUE1 = new ImageIcon("src/recursos/Quicksilver/ataque1.png").getImage();
    private final Image ROCKET_ATAQUE1 = new ImageIcon("src/recursos/Rocket/ataque1.png").getImage();
    private final Image ULTRON_ATAQUE1 = new ImageIcon("src/recursos/Ultron/ataque1.png").getImage();
    private final Image VENOM_ATAQUE1 = new ImageIcon("src/recursos/Venom/ataque1.png").getImage();
    private final Image VIPER_ATAQUE1 = new ImageIcon("src/recursos/Viper/ataque1.png").getImage();
    
    private String nombrePersonaje;
    private Image foto;
    private String numJugador;
    
    /**
     * Creates new form SpritePersonaje
     * @param nombrePersonaje
     * @param numJugador
     */
    public SpritePersonaje(String nombrePersonaje, String numJugador) {
        this.nombrePersonaje = nombrePersonaje;
        this.numJugador = numJugador;
        initComponents();
    }
    public SpritePersonaje(){
        
    }
    
    @Override
    public void paint(Graphics g){
        switch (nombrePersonaje) {
            case "BrujaEscarlata" -> foto = BRUJAESCARLATA_ATAQUE1;
            case "Carnage" -> foto = CARNAGE_ATAQUE1;
            case "Daredevil" -> foto = DAREDEVIL_ATAQUE1;
            case "Deadpool" -> foto = DEADPOOL_ATAQUE1;
            case "Morgan" -> foto = MORGAN_ATAQUE1;
            case "Quicksilver" -> foto = QUICKSILVER_ATAQUE1;
            case "Rocket" -> foto = ROCKET_ATAQUE1;
            case "Ultron" -> foto = ULTRON_ATAQUE1;
            case "Venom" -> foto = VENOM_ATAQUE1;
            case "Viper" -> foto = VIPER_ATAQUE1;
            default -> {
            }
        }
        Graphics2D g2D = (Graphics2D) g;
        int altura = (foto.getHeight(this));
        int ancho = foto.getWidth(this);
        if ("1".equals(numJugador)){
            g2D.drawImage(foto, 0, 300 - altura, ancho, altura, null);
        } else {
            g2D.drawImage(foto, 0 + ancho, 300 - altura, -ancho, altura, null);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpritePersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SpritePersonaje().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
}


